In [22]:
import numpy as np
import pandas as pd

import re
import matplotlib.pyplot as plt

In [2]:
import torch

In [3]:
import torchvision

In [92]:
from torch import nn
import torch.optim as opt

In [5]:
train_data = torchvision.datasets.FashionMNIST(
    root="data",
    train=True,
    download=True,
    transform=torchvision.transforms.ToTensor()
)


Extracting data/FashionMNIST/raw/train-images-idx3-ubyte.gz to data/FashionMNIST/raw




Extracting data/FashionMNIST/raw/train-labels-idx1-ubyte.gz to data/FashionMNIST/raw




Extracting data/FashionMNIST/raw/t10k-images-idx3-ubyte.gz to data/FashionMNIST/raw




Extracting data/FashionMNIST/raw/t10k-labels-idx1-ubyte.gz to data/FashionMNIST/raw

Processing...
Done!


/Users/sakiura/.pyenv/versions/Anaconda3-2020.11/lib/python3.8/site-packages/torchvision/datasets/mnist.py:502: UserWarning: The given NumPy array is not writeable, and PyTorch does not support non-writeable tensors. This means you can write to the underlying (supposedly non-writeable) NumPy array using the tensor. You may want to copy the array to protect its data or make it writeable before converting it to a tensor. This type of warning will be suppressed for the rest of this program. (Triggered internally at  /Users/distiller/project/conda/conda-bld/pytorch_1616554845587/work/torch/csrc/utils/tensor_numpy.cpp:143.)
  return torch.from_numpy(parsed.astype(m[2], copy=False)).view(*s)


In [6]:
train_data

Dataset FashionMNIST
    Number of datapoints: 60000
    Root location: data
    Split: Train
    StandardTransform
Transform: ToTensor()

In [10]:
test_data = torchvision.datasets.FashionMNIST(
    root="data",
    train=False,
    download=True,
    transform=torchvision.transforms.ToTensor()
)

In [11]:
test_data

Dataset FashionMNIST
    Number of datapoints: 10000
    Root location: data
    Split: Test
    StandardTransform
Transform: ToTensor()

In [53]:
img_data = train_data.data
img_label = train_data.targets

torch.Size([60000])

In [57]:
device = 'cuda' if torch.cuda.is_available() else 'cpu'
print('Using {} device'.format(device))

Using cpu device


In [58]:
class model(nn.Module):
    def __init__(self):
        super(model, self).__init__()
        self.flatten = nn.Flatten()
        self.linear_relu = nn.Sequential(
            nn.Linear(28*28, 512),
            nn.ReLU(),
            nn.Linear(512,512),
            nn.ReLU(),
            nn.Linear(512,10),
            nn.ReLU()
        )
    def forward(self,x):
        x = self.flatten(x)
        logstic = self.linear_relu(x)
        return logstic

In [60]:
model = model()

In [61]:
model

model(
  (flatten): Flatten(start_dim=1, end_dim=-1)
  (linear_relu): Sequential(
    (0): Linear(in_features=784, out_features=512, bias=True)
    (1): ReLU()
    (2): Linear(in_features=512, out_features=512, bias=True)
    (3): ReLU()
    (4): Linear(in_features=512, out_features=10, bias=True)
    (5): ReLU()
  )
)

In [81]:
# model.forward(img_data)
X = torch.rand(1, 28, 28, device=device)
print(X.size())
logits = model(X)
pred_probab = nn.Softmax(dim=1)(logits)
pred_probab

torch.Size([1, 28, 28])


tensor([[0.1021, 0.1077, 0.1025, 0.0970, 0.0970, 0.1032, 0.0970, 0.0970, 0.0998,
         0.0970]], grad_fn=<SoftmaxBackward>)

In [91]:
for name,param in model.named_parameters():
    print(name)
    print(param)

linear_relu.0.weight
Parameter containing:
tensor([[ 0.0234, -0.0285,  0.0266,  ...,  0.0280,  0.0154,  0.0190],
        [-0.0191,  0.0237,  0.0191,  ..., -0.0290,  0.0171, -0.0234],
        [ 0.0187, -0.0335, -0.0087,  ...,  0.0069, -0.0209,  0.0219],
        ...,
        [ 0.0224,  0.0082, -0.0003,  ..., -0.0111, -0.0169, -0.0213],
        [-0.0313,  0.0035, -0.0278,  ...,  0.0196, -0.0118,  0.0310],
        [-0.0112,  0.0231,  0.0165,  ...,  0.0129, -0.0098, -0.0164]],
       requires_grad=True)
linear_relu.0.bias
Parameter containing:
tensor([-0.0339, -0.0349, -0.0337,  0.0269, -0.0113, -0.0306,  0.0291,  0.0264,
         0.0042,  0.0222, -0.0354,  0.0215, -0.0282,  0.0240,  0.0071, -0.0205,
         0.0315, -0.0295, -0.0264,  0.0117, -0.0295,  0.0046,  0.0166, -0.0204,
        -0.0130, -0.0025,  0.0291,  0.0135,  0.0102, -0.0012, -0.0231, -0.0280,
        -0.0122, -0.0164, -0.0343,  0.0207, -0.0067,  0.0128,  0.0305,  0.0349,
         0.0221,  0.0209,  0.0226, -0.0032, -0.0344,  0

In [93]:
model.linear_relu

Sequential(
  (0): Linear(in_features=784, out_features=512, bias=True)
  (1): ReLU()
  (2): Linear(in_features=512, out_features=512, bias=True)
  (3): ReLU()
  (4): Linear(in_features=512, out_features=10, bias=True)
  (5): ReLU()
)